[project]
name = "youtube-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "panda>=0.3.1",
    "requests>=2.32.5",
]
